"""empty message

Revision ID: f2a79e684b1b
Revises: e29311834563
Create Date: 2020-09-14 00:18:01.981662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2a79e684b1b'
down_revision = 'e29311834563'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=30), nullable=True),
    sa.Column('e_mail', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('e_mail'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
